[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
chrono = "0.4.37"
dotenvy = "0.15.7"
futures = "0.3"
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
sea-orm = { version = "0.12.15", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
serde = "1.0.197"
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# Local patches - typically git references
[patch.crates-io]
