[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
edition = "2021"
publish = false

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
base64 = "0.22"
cargo_metadata = "0.18"
chrono = "0.4.37"
csv = "1.1.0"
dotenvy = "0.15.7"
futures = "0.3"
git2 = "0.19.0"
lazy_static = "1.4.0"
log = "0.4.21"
neo4rs = "0.7.1"
once_cell = "1.8.0"
pretty_env_logger = "0.5"
rayon = "1.5"
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
sea-orm = { version = "0.12.15", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
ssh2 = "0.9.4"
structopt = { version = "0.3", default-features = false }
tempfile = "3.10.1"
tokio = { version = "1.36", features = ["full"] }
toml = "0.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tugraph = "0.1.4"
tugraph-plugin-util = "0.1.2"
url = "2.2.2"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
walkdir = "2.3"

# Local patches - typically git references
[patch.crates-io]
